INSERT INTO tb_usuarios(email, username, password) VALUES ('caiobiscas@gmail.com', 'biscas', 'abc123');
INSERT INTO tb_usuarios(email, username, password) VALUES ('josh@gmail.com', 'josh', 'abc123');
INSERT INTO tb_usuarios(email, username, password) VALUES ('zoe@gmail.com', 'zoe', 'abc123');
INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('First', 'Esta obra digital é uma jornada épica através das eras, capturando momentos históricos e revivendo-os de maneira única.', 999.99, 3, 'https://einvestidor.estadao.com.br/wp-content/uploads/2021/09/boredape_150920212720.jpg', 1);
INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('Mystic', 'Entre em um mundo misterioso e mágico com este NFT. O portal místico convida você a atravessar para um reino de maravilhas inexplicáveis.', 199.99, 100, 'https://s2.glbimg.com/6fLjMPYo50gB1llNwE11EVXdf8w=/620x430/e.glbimg.com/og/ed/f/original/2022/02/21/https___hypebeast.com_image_2021_10_bored-ape-yacht-club-nft-3-4-million-record-sothebys-metaverse-0.jpg', 1);
INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('Cyber Scape', 'Esta obra leva você a um mundo de sonhos cibernéticos, onde a realidade se funde com o virtual.', 87.99, 50, 'https://thumbor.forbes.com/thumbor/fit-in/x/https://www.forbes.com/advisor/in/wp-content/uploads/2022/03/monkey-g412399084_1280.jpg', 2);
INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('Symphony', 'Deixe-se levar pela harmonia cósmica deste NFT. Cada elemento desta obra representa uma sinfonia celeste única, onde as estrelas dançam em perfeita sintonia. Uma experiência transcendental aguarda.', 1499.99, 30, 'https://conteudo.imguol.com.br/c/noticias/74/2022/06/06/bored-ape-nft-que-integra-a-colecao-do-bored-ape-yacht-club-1654521934017_v2_4x3.jpg', 2);

INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('Voyage', 'Esta obra digital é uma jornada épica através das eras, capturando momentos históricos e revivendo-os de maneira única.', 999.99, 3, 'https://einvestidor.estadao.com.br/wp-content/uploads/2021/09/boredape_150920212720.jpg', 1);
INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('Mystic', 'Entre em um mundo misterioso e mágico com este NFT. O portal místico convida você a atravessar para um reino de maravilhas inexplicáveis.', 199.99, 100, 'https://s2.glbimg.com/6fLjMPYo50gB1llNwE11EVXdf8w=/620x430/e.glbimg.com/og/ed/f/original/2022/02/21/https___hypebeast.com_image_2021_10_bored-ape-yacht-club-nft-3-4-million-record-sothebys-metaverse-0.jpg', 1);
INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('Cyber Scape', 'Esta obra leva você a um mundo de sonhos cibernéticos, onde a realidade se funde com o virtual.', 87.99, 50, 'https://thumbor.forbes.com/thumbor/fit-in/x/https://www.forbes.com/advisor/in/wp-content/uploads/2022/03/monkey-g412399084_1280.jpg', 2);
INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('Symphony', 'Deixe-se levar pela harmonia cósmica deste NFT. Cada elemento desta obra representa uma sinfonia celeste única, onde as estrelas dançam em perfeita sintonia. Uma experiência transcendental aguarda.', 1499.99, 30, 'https://conteudo.imguol.com.br/c/noticias/74/2022/06/06/bored-ape-nft-que-integra-a-colecao-do-bored-ape-yacht-club-1654521934017_v2_4x3.jpg', 2);

INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('Voyage', 'Esta obra digital é uma jornada épica através das eras, capturando momentos históricos e revivendo-os de maneira única.', 999.99, 3, 'https://einvestidor.estadao.com.br/wp-content/uploads/2021/09/boredape_150920212720.jpg', 1);
INSERT INTO tb_nft(name, description, price, qtd, img_url, user_id) VALUES ('Second', 'Entre em um mundo misterioso e mágico com este NFT. O portal místico convida você a atravessar para um reino de maravilhas inexplicáveis.', 199.99, 100, 'https://s2.glbimg.com/6fLjMPYo50gB1llNwE11EVXdf8w=/620x430/e.glbimg.com/og/ed/f/original/2022/02/21/https___hypebeast.com_image_2021_10_bored-ape-yacht-club-nft-3-4-million-record-sothebys-metaverse-0.jpg', 1);